---
title: "NY DEC Wetlands GHG"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: setup


library(formatR)
knitr::opts_chunk$set(echo = FALSE, fig.align = "center", fig.show = "hold", warning = FALSE,
                      message = FALSE, dpi = 100, tidy.opts = list(width.cutoff = 60), tidy = T, collapse = TRUE, root.dir = '/Users/Anthony/')


library(tidyverse)
library(googledrive) 
library(terra)
library(readxl)
```



Find data 

- ADK Processing folder

```{r}
files = drive_find(pattern = "Clean_Flux_2024", type = "spreadsheet")

drive_download(file = as_id(files$id[[1]]), path = "/Users/Anthony/Data and Analysis Local/FieldData/Clean_Flux_2024.xlsx",
               overwrite = TRUE)
```


```{r}

locs <- read_xlsx("/Users/Anthony/Data and Analysis Local/FieldData/NYDEC_Wetland_Loc.xlsx")
ghg <- read_xlsx("/Users/Anthony/Data and Analysis Local/FieldData/Clean_Flux_2024.xlsx")

locs$`Site Code`
ghg$Unique_ID
```

```{r}
df <- read_xlsx(path = "/Users/Anthony/Data and Analysis Local/FieldData/NYDEC_Wetland_Loc.xlsx", 
                trim_ws = T) |> dplyr::rename_with(~ str_replace_all(.x, "\\s+", "_")) |> 
    dplyr::mutate(Lat = as.numeric(str_trim(str_split_fixed(Lat_Long, ",", 2)[,1])),
                  Lon = as.numeric(str_trim(str_split_fixed(Lat_Long, ",", 2)[,2]))) |> 
    filter(!is.na(Lat) | !is.na(Lon))

View(df)


v <- vect(df, geom = c("Lon", "Lat"), crs = "EPSG:4326")
plot(v)

writeVector(v, "/Users/Anthony/Data and Analysis Local/FieldData/NYDEC_Wetland_Loc.gpkg", overwrite = T)

```

